# config/api.yml

api.add_playlist:
  path:     /playlist/item
  defaults: { _controller: 'ColaRadio\ApiController::playlistItemPostAction'}
  methods: [POST]

api.playlist:
  path:     /playlist/{id}
  defaults: { _controller: 'ColaRadio\ApiController::playlistAction'}
  methods: [GET]

api.my_playlist:
  path:     /playlist/
  defaults: { _controller: 'ColaRadio\ApiController::playlistAction', id:0}

api.user:
  path:     /user/{id}
  defaults: { _controller: 'ColaRadio\ApiController::userAction'}

api.my_user:
  path:     /user/
  defaults: { _controller: 'ColaRadio\ApiController::userAction',id:0}



