# routes.yml

home:
  path: /
  defaults: { _controller: 'ColaRadio\AppController::indexAction' }

login_form:
  path: /login
  defaults: { _controller: 'ColaRadio\AppController::loginAction' }

playlist:
  path: /playlist
  defaults: { _controller: 'ColaRadio\AppController::playlistAction' }


api:
  prefix: /api
  resource: api.yml

blog:
  prefix: /blog
  resource: blog.yml